### PR TITLE
fix biocore/qiime#2007

### PR DESCRIPTION
**Pull request by antgonza**
Let's try again.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Looks good, thanks! Did you test this locally for cases where swarm completes successfully and not successfully? Just want to confirm as these aren't automatically tested unfortunately.

**Comment by antgonza** [comment]
Is testing important? :wink: 

```bash
(qiime)10:43:19 burrito-fillings@fix-qiime-2014-v2$ pick_otus.py -m swarm -i seqs.fna
Traceback (most recent call last):
  File "/Users/antoniog/svn_programs/qiime/scripts/pick_otus.py", line 1004, in <module>
    main()
  File "/Users/antoniog/svn_programs/qiime/scripts/pick_otus.py", line 995, in main
    result_path=result_path, log_path=log_path)
  File "/Users/antoniog/svn_programs/qiime/qiime/pick_otus.py", line 774, in __call__
    HALT_EXEC=False)
  File "/Users/antoniog/svn_programs/burrito-fillings/bfillings/swarm_v127.py", line 294, in swarm_denovo_cluster
    clusters = swarm(seq_path)
  File "/Users/antoniog/svn_programs/burrito-fillings/bfillings/swarm_v127.py", line 77, in __call__
    super(Swarm, self).__call__(seq_path)
  File "/Users/antoniog/.virtualenvs/qiime/lib/python2.7/site-packages/burrito/util.py", line 284, in __call__
    'StdErr:\n%s\n' % open(errfile).read())
burrito.util.ApplicationError: Unacceptable application exit status: 1
Command:
cd "/Users/antoniog/svn_programs/burrito-fillings/"; swarm -d 1 -o "/var/folders/17/c40mmrx56w918s7lp6ds2jvw0000gq/T/temp_otumap__xh2K9.swarm" -t 1 /var/folders/17/c40mmrx56w918s7lp6ds2jvw0000gq/T/SwarmExactMatchFilterQwacbb.fasta > "/tmp/tmpyA3C6yEVYHVd8KAeac8I.txt" 2> "/tmp/tmpONVCBaIClmHjGm6yb7WR.txt"
StdOut:

StdErr:
Swarm 1.2.19 [May  7 2015 18:24:07]
Copyright (C) 2012-2014 Torbjorn Rognes and Frederic Mahe
https://github.com/torognes/swarm

Please cite: Mahe F, Rognes T, Quince C, de Vargas C, Dunthorn M (2014)
Swarm: robust and fast clustering method for amplicon-based studies.
PeerJ 2:e593 http://dx.doi.org/10.7717/peerj.593

CPU features:      mmx sse sse2 sse3 ssse3 sse4.1 sse4.2 popcnt avx avx2
Database file:     /var/folders/17/c40mmrx56w918s7lp6ds2jvw0000gq/T/SwarmExactMatchFilterQwacbb.fasta
Output file:       /var/folders/17/c40mmrx56w918s7lp6ds2jvw0000gq/T/temp_otumap__xh2K9.swarm
Resolution (d):    1
Threads:           1
Algorithm:         regular
Scores:            match: 5, mismatch: -4
Gap penalties:     opening: 12, extension: 4
Converted costs:   mismatch: 9, gap opening: 12, gap extension: 7

Reading database:  0%Error: Illegal character 'N' in sequence on line 2


(qiime)10:43:25 burrito-fillings@fix-qiime-2014-v2$ echo -e '>S1\nAAAAA\n>S2\nAAAA' > seqs.fna
(qiime)10:43:36 burrito-fillings@fix-qiime-2014-v2$ pick_otus.py -m swarm -i seqs.fna ; more swarm_picked_otus/seqs_otus.txt
denovo0 S2      S1
```

**Comment by gregcaporaso** [comment]
Excellent, thanks!

**Comment by jairideout** [comment]
Note that this fixes https://github.com/biocore/qiime/issues/2014, *not* https://github.com/biocore/qiime/issues/2007

**Pull request merged**
